### ISSUE TITLE
Error: Cannot find module '@angular-devkit/core'

### ISSUE THREAD

**Issue by Xsylum** [Xsylum/angular-tutorial#6]
Linked to https://github.com/angular/angular-cli/issues/9307

```
PS D:\G33k_Zone\Angular\tutorial\auth0> ng generate service AuthService
module.js:471
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\G33k_Zone\Angular\tutorial\auth0\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by Xsylum** [comment]
Solution:
uninstall angular/cli and reinstall it
